#!/usr/bin/env bun
/**
 * Ironclad Bead System Initialization Script
 *
 * Run this once to initialize the Bead system in your SAM project.
 *
 * Usage: bun run bead-init.ts
 */

import { beadFactory } from './backend/src/services/BeadFactory'
import { existsSync, writeFileSync } from 'fs'
import { join } from 'path'

async function main() {
  console.log('🔮 Initializing Ironclad Bead System...')

  // 1. Initialize bead directory
  await beadFactory.initialize()

  // 2. Add gitignore entry if it doesn't exist
  const gitignorePath = join(process.cwd(), '.gitignore')
  let gitignoreContent = ''

  if (existsSync(gitignorePath)) {
    const fs = require('fs').promises
    gitignoreContent = await fs.readFile(gitignorePath, 'utf-8')
  }

  if (!gitignoreContent.includes('.beads/')) {
    gitignoreContent += '\n# Ironclad Beads (until indexed)\n.beads/\n'
    writeFileSync(gitignorePath, gitignoreContent)
    console.log('✅ Added .beads/ to .gitignore')
  }

  // 3. Create types file for TypeScript
  const typesPath = join(process.cwd(), 'backend', 'src', 'types', 'IroncladBead.ts')
  const typesContent = `/**
 * Ironclad Bead Type Definitions
 * Auto-generated by bead-init.ts
 */

export type BeadType = 'thought' | 'tool_use' | 'tool_result' | 'error' | 'handoff' | 'output' | 'api_request' | 'api_response' | 'complete' | 'failed' | 'system_context'

export interface IroncladBead {
  id: string
  parent_id: string
  agent_id: string
  sequence: number

  cost_metadata: {
    input_tokens: number
    output_tokens: number
    model: string
    cost_usd: number
  }

  type: BeadType
  content: any

  vector_status: 'pending' | 'indexed' | 'skipped'
  significance_score: number

  timestamp: string
  workflow_id?: string
  metadata?: Record<string, any>
}

export interface BeadCreationOptions {
  sessionId: string
  workflowId?: string
  parentBeadId?: string
  forceSignificance?: number
}
`

  const fs = require('fs').promises
  try {
    // Ensure directory exists
    await fs.mkdir(join(process.cwd(), 'backend', 'src', 'types'), { recursive: true })
    await fs.writeFile(typesPath, typesContent)
    console.log('✅ Created type definitions')
  } catch (error) {
    console.warn('⚠️  Could not create types file:', error)
  }

  // 4. Display integration instructions
  console.log('\n🎉 Ironclad Bead System Initialized!')
  console.log('\n📋 NEXT STEPS:')
  console.log('1. Apply the integration patch to SessionLauncher.ts')
  console.log('   Run: cat backend/src/services/BeadLauncherPatch.ts')
  console.log('')
  console.log('2. Test with a simple agent session')
  console.log('   The .beads/ directory will populate with JSON files')
  console.log('')
  console.log('3. Move to Phase 2: Create the Archivist watcher')
  console.log('   (See Phase 2 implementation guide)')
  console.log('')
  console.log('💡 Existing functionality continues unchanged!')
  console.log('   Beads are written as a sidecar - no breaking changes.')
}

main().catch(console.error)