#!/usr/bin/env python3
# /// script
# dependencies = [
#     "click",
#     "mcp",
# ]
# ///

"""
Adapter script for MCP Tool: get_event
Generated by Super Agent Monitor
"""

import sys
import json
import click
from pathlib import Path

# Add original MCP server directory to path
sys.path.append(str(Path("/Users/macuser/git/0MY_PROJECTS/super_agent_monitor/beyond-mcp/apps/1_mcp_server")))

# Import the original module
try:
    import server as original_module
except ImportError as e:
    print(f"Error importing original module: {e}", file=sys.stderr)
    sys.exit(1)

@click.command()
@click.option('--event-ticker', help='event_ticker', type=click.STRING)
@click.option('--with-markets', help='with_markets', type=click.BOOL)
@click.option('--json', 'output_json', is_flag=True, help='Output as JSON')
def main(event_ticker, with_markets, output_json):
    """
    Get detailed information for a specific event.

Args:
    event_ticker: Event ticker (e.g., 'KXELONMARS-99')
    with_markets: Include nested markets in the response

Returns:
    Dict with 'event' object and 'markets' array
    """
    try:
        # Call the original function
        # Note: We access the function directly from the module
        # If the function is decorated, we might need to access the underlying function
        # But usually calling the decorated function works if it returns the value
        
        if hasattr(original_module, 'get_event'):
            func = getattr(original_module, 'get_event')
            result = func(event_ticker=event_ticker, with_markets=with_markets)
            
            if output_json:
                print(json.dumps(result, indent=2))
            else:
                # Simple formatted output
                print(f"Result for get_event:")
                print(json.dumps(result, indent=2))
        else:
            print(f"Function get_event not found in module", file=sys.stderr)
            sys.exit(1)
            
    except Exception as e:
        if output_json:
            print(json.dumps({"error": str(e)}))
        else:
            print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
