#!/usr/bin/env python3
# /// script
# dependencies = [
#     "click",
#     "mcp",
# ]
# ///

"""
Adapter script for MCP Tool: get_event_candlesticks
Generated by Super Agent Monitor
"""

import sys
import json
import click
from pathlib import Path

# Add original MCP server directory to path
sys.path.append(str(Path("/Users/macuser/git/0MY_PROJECTS/super_agent_monitor/beyond-mcp/apps/1_mcp_server")))

# Import the original module
try:
    import server as original_module
except ImportError as e:
    print(f"Error importing original module: {e}", file=sys.stderr)
    sys.exit(1)

@click.command()
@click.option('--series-ticker', help='series_ticker', type=click.STRING)
@click.option('--event-ticker', help='event_ticker', type=click.STRING)
@click.option('--start-ts', help='start_ts', type=click.INT)
@click.option('--end-ts', help='end_ts', type=click.INT)
@click.option('--interval', help='interval', type=click.INT)
@click.option('--json', 'output_json', is_flag=True, help='Output as JSON')
def main(series_ticker, event_ticker, start_ts, end_ts, interval, output_json):
    """
    Get candlestick data aggregated across all markets in an event.

Args:
    series_ticker: Series ticker
    event_ticker: Event ticker
    start_ts: Start timestamp (Unix timestamp)
    end_ts: End timestamp (Unix timestamp)
    interval: Period interval in minutes - 1, 60, or 1440

Returns:
    Dict with 'market_tickers', 'market_candlesticks', and 'adjusted_end_ts'
    """
    try:
        # Call the original function
        # Note: We access the function directly from the module
        # If the function is decorated, we might need to access the underlying function
        # But usually calling the decorated function works if it returns the value
        
        if hasattr(original_module, 'get_event_candlesticks'):
            func = getattr(original_module, 'get_event_candlesticks')
            result = func(series_ticker=series_ticker, event_ticker=event_ticker, start_ts=start_ts, end_ts=end_ts, interval=interval)
            
            if output_json:
                print(json.dumps(result, indent=2))
            else:
                # Simple formatted output
                print(f"Result for get_event_candlesticks:")
                print(json.dumps(result, indent=2))
        else:
            print(f"Function get_event_candlesticks not found in module", file=sys.stderr)
            sys.exit(1)
            
    except Exception as e:
        if output_json:
            print(json.dumps({"error": str(e)}))
        else:
            print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
