#!/usr/bin/env python3
# /// script
# dependencies = [
#     "click",
#     "mcp",
# ]
# ///

"""
Adapter script for MCP Tool: get_exchange_status
Generated by Super Agent Monitor
"""

import sys
import json
import click
from pathlib import Path

# Add original MCP server directory to path
sys.path.append(str(Path("/Users/macuser/git/0MY_PROJECTS/super_agent_monitor/beyond-mcp/apps/1_mcp_server")))

# Import the original module
try:
    import server as original_module
except ImportError as e:
    print(f"Error importing original module: {e}", file=sys.stderr)
    sys.exit(1)

@click.command()

@click.option('--json', 'output_json', is_flag=True, help='Output as JSON')
def main(output_json):
    """
    Get the current Kalshi exchange status.

Returns exchange_active, trading_active, and estimated_resume_time.
    """
    try:
        # Call the original function
        # Note: We access the function directly from the module
        # If the function is decorated, we might need to access the underlying function
        # But usually calling the decorated function works if it returns the value
        
        if hasattr(original_module, 'get_exchange_status'):
            func = getattr(original_module, 'get_exchange_status')
            result = func()
            
            if output_json:
                print(json.dumps(result, indent=2))
            else:
                # Simple formatted output
                print(f"Result for get_exchange_status:")
                print(json.dumps(result, indent=2))
        else:
            print(f"Function get_exchange_status not found in module", file=sys.stderr)
            sys.exit(1)
            
    except Exception as e:
        if output_json:
            print(json.dumps({"error": str(e)}))
        else:
            print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
