#!/usr/bin/env python3
# /// script
# dependencies = [
#     "click",
#     "mcp",
# ]
# ///

"""
Adapter script for MCP Tool: get_market_orderbook
Generated by Super Agent Monitor
"""

import sys
import json
import click
from pathlib import Path

# Add original MCP server directory to path
sys.path.append(str(Path("/Users/macuser/git/0MY_PROJECTS/super_agent_monitor/beyond-mcp/apps/1_mcp_server")))

# Import the original module
try:
    import server as original_module
except ImportError as e:
    print(f"Error importing original module: {e}", file=sys.stderr)
    sys.exit(1)

@click.command()
@click.option('--ticker', help='ticker', type=click.STRING)
@click.option('--depth', help='depth', type=click.INT)
@click.option('--json', 'output_json', is_flag=True, help='Output as JSON')
def main(ticker, depth, output_json):
    """
    Get the orderbook for a specific market.

Args:
    ticker: Market ticker symbol
    depth: Orderbook depth (0 = all levels, 1-100 for specific depth, default: 10)

Returns:
    Dict with 'orderbook' containing yes/no bid arrays
    """
    try:
        # Call the original function
        # Note: We access the function directly from the module
        # If the function is decorated, we might need to access the underlying function
        # But usually calling the decorated function works if it returns the value
        
        if hasattr(original_module, 'get_market_orderbook'):
            func = getattr(original_module, 'get_market_orderbook')
            result = func(ticker=ticker, depth=depth)
            
            if output_json:
                print(json.dumps(result, indent=2))
            else:
                # Simple formatted output
                print(f"Result for get_market_orderbook:")
                print(json.dumps(result, indent=2))
        else:
            print(f"Function get_market_orderbook not found in module", file=sys.stderr)
            sys.exit(1)
            
    except Exception as e:
        if output_json:
            print(json.dumps({"error": str(e)}))
        else:
            print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
