#!/usr/bin/env python3
# /// script
# dependencies = [
#     "click",
#     "mcp",
# ]
# ///

"""
Adapter script for MCP Tool: get_recent_trades
Generated by Super Agent Monitor
"""

import sys
import json
import click
from pathlib import Path

# Add original MCP server directory to path
sys.path.append(str(Path("/Users/macuser/git/0MY_PROJECTS/super_agent_monitor/beyond-mcp/apps/1_mcp_server")))

# Import the original module
try:
    import server as original_module
except ImportError as e:
    print(f"Error importing original module: {e}", file=sys.stderr)
    sys.exit(1)

@click.command()
@click.option('--limit', help='limit', type=click.INT)
@click.option('--ticker', help='ticker', type=click.STRING)
@click.option('--min-ts', help='min_ts', type=click.STRING)
@click.option('--max-ts', help='max_ts', type=click.STRING)
@click.option('--cursor', help='cursor', type=click.STRING)
@click.option('--json', 'output_json', is_flag=True, help='Output as JSON')
def main(limit, ticker, min_ts, max_ts, cursor, output_json):
    """
    Get recent trades across markets or for a specific market.

Args:
    limit: Number of trades to return (1-1000, default: 10)
    ticker: Filter trades for specific market ticker
    min_ts: Filter trades after this Unix timestamp
    max_ts: Filter trades before this Unix timestamp
    cursor: Pagination cursor

Returns:
    Dict with 'trades' array and optional 'cursor'
    """
    try:
        # Call the original function
        # Note: We access the function directly from the module
        # If the function is decorated, we might need to access the underlying function
        # But usually calling the decorated function works if it returns the value
        
        if hasattr(original_module, 'get_recent_trades'):
            func = getattr(original_module, 'get_recent_trades')
            result = func(limit=limit, ticker=ticker, min_ts=min_ts, max_ts=max_ts, cursor=cursor)
            
            if output_json:
                print(json.dumps(result, indent=2))
            else:
                # Simple formatted output
                print(f"Result for get_recent_trades:")
                print(json.dumps(result, indent=2))
        else:
            print(f"Function get_recent_trades not found in module", file=sys.stderr)
            sys.exit(1)
            
    except Exception as e:
        if output_json:
            print(json.dumps({"error": str(e)}))
        else:
            print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
