#!/usr/bin/env python3
# /// script
# dependencies = [
#     "click",
#     "mcp",
# ]
# ///

"""
Adapter script for MCP Tool: list_markets
Generated by Super Agent Monitor
"""

import sys
import json
import click
from pathlib import Path

# Add original MCP server directory to path
sys.path.append(str(Path("/Users/macuser/git/0MY_PROJECTS/super_agent_monitor/beyond-mcp/apps/1_mcp_server")))

# Import the original module
try:
    import server as original_module
except ImportError as e:
    print(f"Error importing original module: {e}", file=sys.stderr)
    sys.exit(1)

@click.command()
@click.option('--limit', help='limit', type=click.INT)
@click.option('--status', help='status', type=click.STRING)
@click.option('--event-ticker', help='event_ticker', type=click.STRING)
@click.option('--series-ticker', help='series_ticker', type=click.STRING)
@click.option('--tickers', help='tickers', type=click.STRING)
@click.option('--mve-filter', help='mve_filter', type=click.STRING)
@click.option('--cursor', help='cursor', type=click.STRING)
@click.option('--json', 'output_json', is_flag=True, help='Output as JSON')
def main(limit, status, event_ticker, series_ticker, tickers, mve_filter, cursor, output_json):
    """
    List Kalshi markets with various filters.

Args:
    limit: Number of markets to return (1-1000, default: 10)
    status: Market status filter - 'open', 'closed', 'settled', or comma-separated
    event_ticker: Filter by event ticker
    series_ticker: Filter by series ticker
    tickers: Filter by market tickers (comma-separated)
    mve_filter: Multivariate events filter - 'only' or 'exclude'
    cursor: Pagination cursor for next page

Returns:
    Dict with 'markets' array and optional 'cursor' for pagination
    """
    try:
        # Call the original function
        # Note: We access the function directly from the module
        # If the function is decorated, we might need to access the underlying function
        # But usually calling the decorated function works if it returns the value
        
        if hasattr(original_module, 'list_markets'):
            func = getattr(original_module, 'list_markets')
            result = func(limit=limit, status=status, event_ticker=event_ticker, series_ticker=series_ticker, tickers=tickers, mve_filter=mve_filter, cursor=cursor)
            
            if output_json:
                print(json.dumps(result, indent=2))
            else:
                # Simple formatted output
                print(f"Result for list_markets:")
                print(json.dumps(result, indent=2))
        else:
            print(f"Function list_markets not found in module", file=sys.stderr)
            sys.exit(1)
            
    except Exception as e:
        if output_json:
            print(json.dumps({"error": str(e)}))
        else:
            print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
