#!/usr/bin/env python3
# /// script
# dependencies = [
#     "click",
#     "mcp",
# ]
# ///

"""
Adapter script for MCP Tool: list_series
Generated by Super Agent Monitor
"""

import sys
import json
import click
from pathlib import Path

# Add original MCP server directory to path
sys.path.append(str(Path("/Users/macuser/git/0MY_PROJECTS/super_agent_monitor/beyond-mcp/apps/1_mcp_server")))

# Import the original module
try:
    import server as original_module
except ImportError as e:
    print(f"Error importing original module: {e}", file=sys.stderr)
    sys.exit(1)

@click.command()
@click.option('--category', help='category', type=click.STRING)
@click.option('--tags', help='tags', type=click.STRING)
@click.option('--with-metadata', help='with_metadata', type=click.BOOL)
@click.option('--json', 'output_json', is_flag=True, help='Output as JSON')
def main(category, tags, with_metadata, output_json):
    """
    List all available series (market templates).

Returns ~6900 series! Use filters to narrow results.

Args:
    category: Filter by category (e.g., 'Politics', 'Economics')
    tags: Filter by tags (comma-separated)
    with_metadata: Include product metadata

Returns:
    Dict with 'series' array containing all matching series
    """
    try:
        # Call the original function
        # Note: We access the function directly from the module
        # If the function is decorated, we might need to access the underlying function
        # But usually calling the decorated function works if it returns the value
        
        if hasattr(original_module, 'list_series'):
            func = getattr(original_module, 'list_series')
            result = func(category=category, tags=tags, with_metadata=with_metadata)
            
            if output_json:
                print(json.dumps(result, indent=2))
            else:
                # Simple formatted output
                print(f"Result for list_series:")
                print(json.dumps(result, indent=2))
        else:
            print(f"Function list_series not found in module", file=sys.stderr)
            sys.exit(1)
            
    except Exception as e:
        if output_json:
            print(json.dumps({"error": str(e)}))
        else:
            print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
