#!/usr/bin/env python3
# /// script
# dependencies = [
#     "click",
#     "mcp",
# ]
# ///

"""
Adapter script for MCP Tool: list_events
Generated by Super Agent Monitor
"""

import sys
import json
import click
from pathlib import Path

# Add original MCP server directory to path
sys.path.append(str(Path("/Users/macuser/git/0MY_PROJECTS/super_agent_monitor/beyond-mcp/apps/1_mcp_server")))

# Import the original module
try:
    import server as original_module
except ImportError as e:
    print(f"Error importing original module: {e}", file=sys.stderr)
    sys.exit(1)

@click.command()
@click.option('--limit', help='limit', type=click.INT)
@click.option('--status', help='status', type=click.STRING)
@click.option('--series-ticker', help='series_ticker', type=click.STRING)
@click.option('--with-markets', help='with_markets', type=click.BOOL)
@click.option('--with-milestones', help='with_milestones', type=click.BOOL)
@click.option('--cursor', help='cursor', type=click.STRING)
@click.option('--json', 'output_json', is_flag=True, help='Output as JSON')
def main(limit, status, series_ticker, with_markets, with_milestones, cursor, output_json):
    """
    List Kalshi events (collections of related markets).

Args:
    limit: Number of events to return (1-200, default: 10)
    status: Event status filter - 'open', 'closed', 'settled'
    series_ticker: Filter by series ticker
    with_markets: Include nested markets in response
    with_milestones: Include related milestones
    cursor: Pagination cursor

Returns:
    Dict with 'events' array, optional 'milestones', and 'cursor'
    """
    try:
        # Call the original function
        # Note: We access the function directly from the module
        # If the function is decorated, we might need to access the underlying function
        # But usually calling the decorated function works if it returns the value
        
        if hasattr(original_module, 'list_events'):
            func = getattr(original_module, 'list_events')
            result = func(limit=limit, status=status, series_ticker=series_ticker, with_markets=with_markets, with_milestones=with_milestones, cursor=cursor)
            
            if output_json:
                print(json.dumps(result, indent=2))
            else:
                # Simple formatted output
                print(f"Result for list_events:")
                print(json.dumps(result, indent=2))
        else:
            print(f"Function list_events not found in module", file=sys.stderr)
            sys.exit(1)
            
    except Exception as e:
        if output_json:
            print(json.dumps({"error": str(e)}))
        else:
            print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
