#!/usr/bin/env python3
# /// script
# dependencies = [
#     "click",
#     "mcp",
# ]
# ///

"""
Adapter script for MCP Tool: list_multivariate_events
Generated by Super Agent Monitor
"""

import sys
import json
import click
from pathlib import Path

# Add original MCP server directory to path
sys.path.append(str(Path("/Users/macuser/git/0MY_PROJECTS/super_agent_monitor/beyond-mcp/apps/1_mcp_server")))

# Import the original module
try:
    import server as original_module
except ImportError as e:
    print(f"Error importing original module: {e}", file=sys.stderr)
    sys.exit(1)

@click.command()
@click.option('--limit', help='limit', type=click.INT)
@click.option('--series-ticker', help='series_ticker', type=click.STRING)
@click.option('--collection-ticker', help='collection_ticker', type=click.STRING)
@click.option('--with-markets', help='with_markets', type=click.BOOL)
@click.option('--cursor', help='cursor', type=click.STRING)
@click.option('--json', 'output_json', is_flag=True, help='Output as JSON')
def main(limit, series_ticker, collection_ticker, with_markets, cursor, output_json):
    """
    Get multivariate (combo) events.

Args:
    limit: Number of events to return (1-200, default: 10)
    series_ticker: Filter by series ticker
    collection_ticker: Filter by collection ticker
    with_markets: Include nested markets
    cursor: Pagination cursor

Returns:
    Dict with 'events' array and 'cursor'
    """
    try:
        # Call the original function
        # Note: We access the function directly from the module
        # If the function is decorated, we might need to access the underlying function
        # But usually calling the decorated function works if it returns the value
        
        if hasattr(original_module, 'list_multivariate_events'):
            func = getattr(original_module, 'list_multivariate_events')
            result = func(limit=limit, series_ticker=series_ticker, collection_ticker=collection_ticker, with_markets=with_markets, cursor=cursor)
            
            if output_json:
                print(json.dumps(result, indent=2))
            else:
                # Simple formatted output
                print(f"Result for list_multivariate_events:")
                print(json.dumps(result, indent=2))
        else:
            print(f"Function list_multivariate_events not found in module", file=sys.stderr)
            sys.exit(1)
            
    except Exception as e:
        if output_json:
            print(json.dumps({"error": str(e)}))
        else:
            print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
