#!/usr/bin/env python3
# /// script
# dependencies = [
#     "click",
#     "mcp",
# ]
# ///

"""
Adapter script for MCP Tool: search_markets
Generated by Super Agent Monitor
"""

import sys
import json
import click
from pathlib import Path

# Add original MCP server directory to path
sys.path.append(str(Path("/Users/macuser/git/0MY_PROJECTS/super_agent_monitor/beyond-mcp/apps/1_mcp_server")))

# Import the original module
try:
    import server as original_module
except ImportError as e:
    print(f"Error importing original module: {e}", file=sys.stderr)
    sys.exit(1)

@click.command()
@click.option('--keyword', help='keyword', type=click.STRING)
@click.option('--limit', help='limit', type=click.INT)
@click.option('--json', 'output_json', is_flag=True, help='Output as JSON')
def main(keyword, limit, output_json):
    """
    Search markets by keyword using cached data.

Searches across market titles, subtitles, and series names.
First search builds cache (~2-5 min), subsequent searches are instant.

Args:
    keyword: Search keyword
    limit: Max results to return (default: 10)

Returns:
    Dict with matching markets
    """
    try:
        # Call the original function
        # Note: We access the function directly from the module
        # If the function is decorated, we might need to access the underlying function
        # But usually calling the decorated function works if it returns the value
        
        if hasattr(original_module, 'search_markets'):
            func = getattr(original_module, 'search_markets')
            result = func(keyword=keyword, limit=limit)
            
            if output_json:
                print(json.dumps(result, indent=2))
            else:
                # Simple formatted output
                print(f"Result for search_markets:")
                print(json.dumps(result, indent=2))
        else:
            print(f"Function search_markets not found in module", file=sys.stderr)
            sys.exit(1)
            
    except Exception as e:
        if output_json:
            print(json.dumps({"error": str(e)}))
        else:
            print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
